## Pandas

In [2]:
import pandas as pd
df = pd.read_csv("data.csv")
print(df.head(5))

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0
3        45  '2020/12/04'    109       175     282.4
4        45  '2020/12/05'    117       148     406.0

In [3]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  32 non-null     int64
 1   Date      31 non-null     object
 2   Pulse     32 non-null     int64
 3   Maxpulse  32 non-null     int64
 4   Calories  30 non-null     float64
dtypes: float64(1), int64(3), object(1)
memory usage: 1.4+ KB
None

In [4]:

print(df.describe())
print("\n")
print(df.describe().T)

         Duration       Pulse    Maxpulse    Calories
count   32.000000   32.000000   32.000000   30.000000
mean    68.437500  103.500000  128.500000  304.680000
std     70.039591    7.832933   12.998759   66.003779
min     30.000000   90.000000  101.000000  195.100000
25%     60.000000  100.000000  120.000000  250.700000
50%     60.000000  102.500000  127.500000  291.200000
75%     60.000000  106.500000  132.250000  343.975000
max    450.000000  130.000000  175.000000  479.000000


          count      mean        std    min    25%    50%      75%    max
Duration   32.0   68.4375  70.039591   30.0   60.0   60.0   60.000  450.0
Pulse      32.0  103.5000   7.832933   90.0  100.0  102.5  106.500  130.0
Maxpulse   32.0  128.5000  12.998759  101.0  120.0  127.5  132.250  175.0
Calories   30.0  304.6800  66.003779  195.1  250.7  291.2  343.975  479.0

In [ ]:
print(df["Calories"].max())
print(df["Calories"].mean())
print(df["Calories"].median())
print(df["Calories"].sum())
print(f"25% of Total Calories is: {df["Calories"].sum() * 25 / 100}")
print(f"50% of Total Calories is: {df["Calories"].sum() * 50 / 100}")

479.0
304.68
291.2
9140.4
25% of Total Calories is: 2285.1
50% of Total Calories is: 4570.2

Duration    0
Date        1
Pulse       0
Maxpulse    0
Calories    2
dtype: int64

In [6]:
df.isnull()

    Duration   Date  Pulse  Maxpulse  Calories
0      False  False  False     False     False
1      False  False  False     False     False
2      False  False  False     False     False
3      False  False  False     False     False
4      False  False  False     False     False
5      False  False  False     False     False
6      False  False  False     False     False
7      False  False  False     False     False
8      False  False  False     False     False
9      False  False  False     False     False
10     False  False  False     False     False
11     False  False  False     False     False
12     False  False  False     False     False
13     False  False  False     False     False
14     False  False  False     False     False
15     False  False  False     False     False
16     False  False  False     False     False
17     False  False  False     False     False
18     False  False  False     False      True
19     False  False  False     False     False
20     False  False  False     False     False
21     False  False  False     False     False
22     False   True  False     False     False
23     False  False  False     False     False
24     False  False  False     False     False
25     False  False  False     False     False
26     False  False  False     False     False
27     False  False  False     False     False
28     False  False  False     False      True
29     False  False  False     False     False
30     False  False  False     False     False
31     False  False  False     False     False

In [7]:
df["Calories"].isnull()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18     True
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28     True
29    False
30    False
31    False
Name: Calories, dtype: bool

In [8]:
# If any specific row has null value in any column
df[df.isnull().any(axis=1)]

    Duration          Date  Pulse  Maxpulse  Calories
18        45  '2020/12/18'     90       112       NaN
22        45           NaN    100       119     282.0
28        60  '2020/12/28'    103       132       NaN

In [9]:
df.isnull().sum()

Duration    0
Date        1
Pulse       0
Maxpulse    0
Calories    2
dtype: int64