In [ ]:
import pandas as pd
df = pd.read_csv("student_sleep_mental_health_2026.csv")
df.head()

,student_id,age,gender,education_level,avg_sleep_hours,screen_time_hours,social_media_hours,study_hours_per_day,exercise_hours_per_week,caffeine_drinks_per_day,stress_level,anxiety_score,gpa,uses_sleep_app,feels_burned_out
2995,2996,23,Non-binary,High School,6.4,9.3,5.5,1.8,2.2,2,8,10,3.58,True,True
2996,2997,23,Male,Undergraduate,6.9,9.1,4.4,2.5,2.8,1,6,5,3.19,True,False
2997,2998,18,Male,Graduate,6.9,7.2,5.9,5.1,4.1,1,9,10,2.47,False,True
2998,2999,22,Male,Undergraduate,7.0,11.3,5.4,2.0,2.2,0,9,10,2.89,True,True
2999,3000,18,Female,Undergraduate,6.9,5.7,4.6,7.5,4.6,2,8,9,2.81,False,True

In [ ]:
df.tail()

In [7]:
df.describe()

,student_id,age,avg_sleep_hours,screen_time_hours,social_media_hours,study_hours_per_day,exercise_hours_per_week,caffeine_drinks_per_day,stress_level,anxiety_score,gpa
count,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000
mean,1500.500000,19.445000,7.414067,6.494667,3.575033,3.235200,3.541900,1.778667,7.216667,7.152000,3.244487
std,866.169729,2.924921,0.971279,2.165014,1.563631,1.405491,2.336889,1.341496,1.572433,1.994882,0.379404
min,1.000000,14.000000,4.400000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.970000
25%,750.750000,17.000000,6.800000,5.000000,2.500000,2.300000,1.800000,1.000000,6.000000,6.000000,2.980000
50%,1500.500000,19.000000,7.400000,6.500000,3.600000,3.200000,3.400000,2.000000,7.000000,7.000000,3.245000
75%,2250.250000,21.000000,8.100000,8.000000,4.600000,4.200000,5.100000,3.000000,8.000000,9.000000,3.510000
max,3000.000000,29.000000,10.900000,13.600000,9.000000,8.700000,11.300000,8.000000,10.000000,10.000000,4.000000

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   student_id               3000 non-null   int64
 1   age                      3000 non-null   int64
 2   gender                   3000 non-null   object
 3   education_level          3000 non-null   object
 4   avg_sleep_hours          3000 non-null   float64
 5   screen_time_hours        3000 non-null   float64
 6   social_media_hours       3000 non-null   float64
 7   study_hours_per_day      3000 non-null   float64
 8   exercise_hours_per_week  3000 non-null   float64
 9   caffeine_drinks_per_day  3000 non-null   int64
 10  stress_level             3000 non-null   int64
 11  anxiety_score            3000 non-null   int64
 12  gpa                      3000 non-null   float64
 13  uses_sleep_app           3000 non-null   bool
 14  feels_burned_out         3000 non-null   bool
dtypes: bool(2), float64(6), int64(5), object(2)
memory usage: 310.7+ KB

In [26]:
# len(df[df["gender"] == 'Male'])
len(df[df["gender"] == 'Female'])
# df[(df["anxiety_score"] == 7) & (df["gpa"] >= 3)]

1410